# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0006_auto_20171014_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='title',
            field=models.CharField(default='image', max_length=140),
            preserve_default=False,
        ),
    ]
