# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0011_auto_20171017_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoos',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zoos',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='zoos',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
