# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.IntegerField()),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
