# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_auto_20170930_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('departments', models.TextField()),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
