# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_colleges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=140)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('industrytype', models.TextField()),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Malls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=140)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Museums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=140)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=140)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=140)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Zoos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=140)),
                ('emailaddress', models.EmailField(max_length=254)),
            ],
        ),
    ]
