# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0005_map'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='map',
            new_name='maps',
        ),
    ]
