# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0007_maps_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
