# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0009_auto_20171016_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='height_field',
            field=models.IntegerField(default=200),
        ),
    ]
