# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-20 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0012_auto_20171019_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoos',
            name='description',
            field=models.TextField(default='wow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zoos',
            name='home_page',
            field=models.URLField(default='wow'),
            preserve_default=False,
        ),
    ]
